// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm92W-uB98VuYIWznN6Kcmg-buAh2EgfU',
    appId: '1:158933022666:web:329216198bc383d653c133',
    messagingSenderId: '158933022666',
    projectId: 'mynotes-flutter-backend-2df30',
    authDomain: 'mynotes-flutter-backend-2df30.firebaseapp.com',
    storageBucket: 'mynotes-flutter-backend-2df30.firebasestorage.app',
    measurementId: 'G-1HEHMZLQDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhnvJ6j359cxlD81dQAY8dG8Au9mMjrlo',
    appId: '1:158933022666:android:18716e7582b198a953c133',
    messagingSenderId: '158933022666',
    projectId: 'mynotes-flutter-backend-2df30',
    storageBucket: 'mynotes-flutter-backend-2df30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkNA04IUbpNEbHS_R6qhLFvQLqthi_Xeo',
    appId: '1:158933022666:ios:81fedb04b6fbf4e553c133',
    messagingSenderId: '158933022666',
    projectId: 'mynotes-flutter-backend-2df30',
    storageBucket: 'mynotes-flutter-backend-2df30.firebasestorage.app',
    iosBundleId: 'social.discussbox.mynotes',
  );
}
